### PR TITLE
Fix Oversized Data transaction error

### LINKED ISSUE #289: Bug :: Oversized transaction error
**Describe the bug**
We often go over the size limit of transactions when submitting batches. This causes our transactions to fail and generally everyone has a bad day.

**Steps to reproduce**
1. Set the transaction calldata size to a number above 132KB (even slightly below this number)
2. Run the full system
3. Observe errors submitting batches

**Expected behavior**
We should never submit transactions above the maximum size.

**Solution**

### Work-around
Reduce the Max L2 Tx calldata size for a batch:

1. Update the l2_geth_subscriber 's task definition to have a lower CANONICAL_CHAIN_BATCH_MAX_CALLDATA_BYTES value (right now it's 90,000)
2. Update the ECS service to reference the new task definition and restart the ECS task so it picks up the new config (stop it, and it'll restart itself)
3. Run this query to delete created but unsubmitted batches so that they will be rebuilt to fit the lower size limit:

```
BEGIN;

UPDATE l2_tx_output
SET 
	canonical_chain_batch_number = NULL,
	canonical_chain_batch_index = NULL
WHERE canonical_chain_batch_number >= *batch number that is erroring*;

DELETE FROM canonical_chain_batch
WHERE batch_number >= *batch number that is erroring*;

COMMIT;
```

### Solution
Since it _should_ be predictable, accurately calculate the total transaction bytes for the L1 rollup tx (including all the rolled up L2 Txs' bytes) and create batches such that _this_ number of bytes is less than or equal to the `CANONICAL_CHAIN_BATCH_MAX_CALLDATA_BYTES` instead of simply making sure that all of the L2 txs being rolled up are under this number.

### PR DESCRIPTION
**Pull request by willmeister**
## Description
Note: This builds off of the `fix_tx_and_root_batch_ordering_issue` branch, so it contains the changes from #296 

This change exactly calculates the size of the L1 Tx to be submitted for a tx sent to `CanonicalTransactionChain.appendSequencerBatch(...)` allowing batch creation to maximize the number of L2 txs to roll up without exceeding the maximum tx size that can be processed by the L1 chain.

## Questions
- Are there any other fields that contribute to serialized L1 or L2 tx size that I'm missing?

### Fixes
- Fixes #289 

## Contributing Agreement

- [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

### CODE REVIEW

File: packages/rollup-core/src/app/constants.ts [hunk 1]
```diff
@@ -44,3 +44,32 @@ export const L2_TO_L1_MESSAGE_PASSER_OVM_ADDRESS =
...
+export const L1_ROLLUP_BATCH_TX_BYTES_PER_L2_TX = 64
+
+/*
+- 32 for nonce
+- 32 for gas price
+- 32 for gas limit
+- 32 for value
+- 32 for R (signature)
+- 32 for S (signature)
+- 2 (at most) for V (signature)
```
Comment (tynes) [inline packages/rollup-core/src/app/constants.ts:72]: Shouldn't this always be two, ie padded to 2 bytes if it is smaller?

Comment (willmeister) [reply packages/rollup-core/src/app/constants.ts:72]: Ahh, so this is the L1 tx, so we won't be padding it like the L2 ones. I could be wrong, but I think V is only 1 byte for mainnet txs because Chain ID is < 255. We only needed to worry about padding for our L2 Chain ID of 420 since it requires more than 1 byte but is able to be represented with 3 hex chars instead of requiring all 4. Either way, we should be fine if we just assume V always takes 2 bytes -- our goal is to not underestimate. Being over by 1 byte worst case should be fine.

File: docker-compose.ci.env [hunk 2]
```diff
@@ -58,37 +58,35 @@ STATE_COMMITMENT_CHAIN_CONTRACT_ADDRESS=0x3A098b2982EC25772f16C57f2C1D0463E052ec
 L1_TO_L2_TRANSACTION_QUEUE_CONTRACT_ADDRESS=0xA1B22bF35196AFCE0927D94ce8ad4C4b7bb6F005      # (Required) The address of the L1ToL2TransactionQueue contract
 SAFETY_TRANSACTION_QUEUE_CONTRACT_ADDRESS=0x3a3BEFB4942cF20A69C8eb4FDB8957223Da57fa2        # (Required) The address of the SafetyTransactionQueue contract
 L1_CHAIN_DATA_PERSISTER_DB_PATH=/mnt/l1-node                                                # (Required) The filepath where to locate (or create) the L1 Chain Data Persister LevelDB database
-L1_EARLIEST_BLOCK=0                                                                   # (Required) The earliest block to sync on L1 to start persisting data
```
Comment (karlfloersch) [inline docker-compose.ci.env:61]: Oh @willmeister I might have forgotten to mention this! @tynes & I discovered that if variables in the `env` files are set to:

```
ENV_VAR=                                                 # Some comment
```

The env variable seems to actually be getting set to the *comment*!!!! This is super scary and could cause some very hard to track down bugs. I don't see any instances in this env file but thought I'd mention it because it could cause grief down the line

File: packages/rollup-core/src/app/constants.ts [hunk 3]
```diff
@@ -44,3 +44,32 @@ export const L2_TO_L1_MESSAGE_PASSER_OVM_ADDRESS =
...
 export const ROLLUP_TX_SIZE_IN_BYTES_MINUS_CALLDATA = 150
+
+/*
+Static bytes: 160
+- 4 (Method ID)
+- 32 (txs byte start)
+- 32 (timestamp)
+- 32 (block number)
+- 32 (starts at index)
+- 32 (number of txs bytes elements)
```
Comment (karlfloersch) [inline packages/rollup-core/src/app/constants.ts:55]: @ben-chain you might be good at double checking to make sure there's nothing missing in these calculations. I don't spot any issues off the top of my head though

File: packages/rollup-core/src/app/data/data-service.ts [hunk 4]
```diff
@@ -481,19 +487,23 @@ export class DefaultDataService implements DataService {
...
+      L1_ROLLUP_BATCH_TX_STATIC_OVERHEAD_BYTES +
+      L1_ROLLUP_BATCH_TX_STATIC_CALLDATA_BYTES
     let lastBlockNumber = -1
     for (const row of res) {
       const rowBytes: number = parseInt(row['calldata_bytes'], 10)
-      totalCalldataBytes += rowBytes
-      if (totalCalldataBytes > maxBatchCalldataBytes) {
+      totalL1TxBytes +=
+        roundToNearestMultipleOf32(rowBytes) +
+        L1_ROLLUP_BATCH_TX_BYTES_PER_L2_TX
```
Comment (karlfloersch) [inline packages/rollup-core/src/app/data/data-service.ts:498]: One idea that I had just reading this is you could potentially even try creating an Ethers `canonicalTxChain: Contract` object and literally calling [`canonicalTxChain.interface. encodeFunctionData(batch)`](https://docs.ethers.io/v5/api/utils/abi/interface/#Interface--encoding) to get the length of the ABI encode object. This is definitely less efficient but it at least does remove some human error.

That said I did double check the numbers so this should return the correct value, I believe

File: packages/rollup-core/src/app/util/environment.ts [hunk 5]
```diff
@@ -299,19 +299,19 @@ export class Environment {
...
-      ? parseInt(process.env.CANONICAL_CHAIN_BATCH_MIN_CALLDATA_BYTES, 10)
+    return process.env.CANONICAL_CHAIN_BATCH_MIN_L2_TX_BYTES
+      ? parseInt(process.env.CANONICAL_CHAIN_BATCH_MIN_L2_TX_BYTES, 10)
       : defaultValue
   }
 
-  public static canonicalChainBatchMaxCalldataBytes(
-    defaultValue: number = 125_000
+  public static canonicalChainMaxBatchTxBytes(
+    defaultValue: number = 110_000
```
Comment (karlfloersch) [inline packages/rollup-core/src/app/util/environment.ts:311]: Nice safety margin

**Review by karlfloersch — APPROVED** [review]
Yay this looks great! My one comment was that in order to get a precise estimate of the ABI encoded calldata you could consider ABI encoding the inputs. It feels a little cheap considering it should be easy to calculate (using our brains) the total number of bytes in each tx calldata, but the upside is it might be a bit more general purpose if we need to change function inputs down the line.

That said, take the suggestion or leave it I think this PR is looking good to go and definitely was a great catch that not only are we getting extra bytes from the standard Ethereum transaction, but also we're getting *tons* of extra bytes from the standard ABI encoding scheme which is used. So inefficient!!!

This LGTM!! 🎉

File: packages/rollup-core/src/app/data/data-service.ts (hunk 4 above)
Comment (willmeister) [reply packages/rollup-core/src/app/data/data-service.ts:498]: I think this could be a good idea as a sanity check at the end, but I was a bit concerned about calling it every iteration on each tx. It's quite possible this concern is unfounded, though, and there would be minimal speed impact calling encode + sign hundreds of times in the worst case. 

I'm happy to change this or to profile it if you think we should, though!
