### PR TITLE
Fixing Tx / State Batch Creation Inconsistencies

### LINKED ISSUE #295: State / Tx batch Ordering Inconsistencies
**Describe the bug**
State root ordering within state commitment chain batches may differ from the transaction ordering with which the state roots are associated. 

The root cause (no pun intended) appears to be that the SQL queries that assemble and order the batches order by different fields that _should_ produce the same result but may not.

**Steps to reproduce**
This is hard to reproduce, as it appears to be non-deterministic and based upon how Postgres assigns the ID of its records, possibly across multiple atomic transactions.

The best way to reproduce is by:
1) Submitting a few hundred transactions in a matter of seconds to the L2 Node without the transaction batch creator or state commitment batch creator running but _with_ the L2 Chain Data Persister running
2) Continue (1) until you run into a situation where there is at least one `l2_tx_output` record that does not appear in the same index when ordering the table's records by `ID` vs by `block_number`
3) Run the state commitment batch creator & transaction batch creator
4) See that the transaction in question appears at a different cumulative index when batched

**Expected behavior**
State commitment batches have state roots which exactly correspond in number and order to the transactions within the transaction batch(es) they are committing to.

**Screenshots**
N/A

**Specifications**
 - Version: Commit [29f2fc6847eca7d5ff90fceae0293916fed1669c](https://github.com/ethereum-optimism/optimism-monorepo/commit/29f2fc6847eca7d5ff90fceae0293916fed1669c)
 - OS: N/A
 - Node Version: N/A

### PR DESCRIPTION
**Pull request by willmeister**
## Description
Fixes an issue where state batches and tx batches may be built in differing orders, leading to fraudulent batches being posted on-chain.

### Fixes
- Fixes #295

## Contributing Agreement

- [x] I have read and understood the [Optimism Contributing Guide and Code of Conduct](https://github.com/ethereum-optimism/optimism-monorepo/blob/master/.github/CONTRIBUTING.md) and am following those guidelines in this pull request.

### CODE REVIEW

File: db/scripts/4_create_views.sql [hunk 1]
```diff
@@ -56,7 +56,7 @@ ORDER BY l1.batch_index ASC
 CREATE OR REPLACE VIEW batchable_l2_only_tx_states
 AS
 
-SELECT tx.*, row_number() over (ORDER BY tx.id ASC) -1 AS row_number
+SELECT tx.*, row_number() over (ORDER BY tx.block_number ASC, tx.tx_index ASC) -1 AS row_number
```
Comment (karlfloersch) [inline db/scripts/4_create_views.sql:59]: Ah so if you have multiple transactions in the same block then you order by the ID, that right? This keeps everything globally ordered

File: packages/rollup-core/test/db/l2-data-service.dbspec.ts [hunk 2]
```diff
@@ -752,8 +819,55 @@ describe('L2 Data Service (will fail if postgres is not running with expected sc
...
+        defaultStateRoot,
         blockNumber
       )
+      tx1.transactionIndex = 0
+      await insertTxOutput(dataService, tx1, BatchSubmissionStatus.FINALIZED)
+
+      const tx2 = createTxOutput(
+        keccak256FromUtf8('tx 2'),
+        defaultStateRoot,
+        blockNumber // Intentionally the same block number
```
Comment (karlfloersch) [inline packages/rollup-core/test/db/l2-data-service.dbspec.ts:868]: 👍

**Review by karlfloersch — APPROVED** [review]
Awesome! This LGTM! Read over all the logic & queries and everything seems to look right! 

🚢

File: db/scripts/4_create_views.sql (hunk 1 above)
Comment (willmeister) [reply db/scripts/4_create_views.sql:59]: I'm trying to replace all ordering on ID since that appears to be at least somewhat nondeterministic under load. If somehow we end up with 2 L2 txs in the same block (we shoudln't, that'd be an issue), we'll order _those_ by the tx index in the block.

Comment (karlfloersch) [reply db/scripts/4_create_views.sql:59]: Ok great, that makes sense
